name: SeleniumIDE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Chrome
      run: | 
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env: 
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test --no-build --verbosity normal
